AWSTemplateFormatVersion: '2010-09-09'
Description: A music search application using a prebuilt Docker AMI.

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName
    Default: n11399589

Resources:
  MusicServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      ImageId: ami-0e25e0874539dd125
      IamInstanceProfile: CAB432-Instance-Role
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: subnet-05a3b8177138c8b14
          AssociatePublicIpAddress: true
          GroupSet:
            - sg-032bd1ff8cf77dbb9
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -xe

          # Only update and install what's needed (no docker)
          apt-get update -y
          apt-get install -y nginx openssl

          # Start Docker (if not already running)
          systemctl enable docker
          systemctl start docker

          # Pull and run app
          aws ecr get-login-password --region ap-southeast-2 \
            | docker login --username AWS --password-stdin 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com
          docker pull 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11399589-assignment1-repo:server
          docker rm -f music-server || true
          docker run -d --restart unless-stopped -p 5000:5000 --name music-server 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11399589-assignment1-repo:server
  
  FavouritesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: jamapp-favourites
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: track_id
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: track_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: JamApp
        - Key: Environment
          Value: Production
  
  FavouritesTableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /jamapp/FavouritesTableName
      Type: String
      Value: !Ref FavouritesTable

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MusicServerInstance
  PublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt MusicServerInstance.PublicIp
  FavouritesTableName:
    Value: !Ref FavouritesTable
    Export:
      Name: JamApp-FavouritesTableName
